describe('Task 3', () => {
    beforeEach(() => {
  
      cy.visit('http://live.demoguru99.com')
  
    })
  
    it.only('cypress test for updating account information', () => {
        cy.get('.skip-account').click()
        cy.get('#header-account > .links > ul > .last > a').click()
        cy.get('#email').type('mike.smith@gmail.com')
        cy.get('#pass').type('12345678')
        cy.get('#send2').click()
        cy.get('.skip-account').click()
        cy.get('#header-account > .links > ul > .first > a').click()
        cy.get(':nth-child(3) > .col2-set > .col-1 > .box > .box-title > a').click()
        cy.get('#firstname').clear().type('Mikael')
        cy.get('#middlename').clear().type('Sam')
        cy.get('#current_password').clear().type('12345678')
        cy.get('.buttons-set > .button').click()
        cy.get('body > div > div > div.main-container.col2-left-layout > div > div.col-main > div > div > ul > li > ul > li > span').should('have.text','The account information has been saved.')

    })
    it('Check the Add new address functionality', () => {
        cy.get('.skip-account').click()
        cy.get('#header-account > .links > ul > .last > a').click()
        cy.get('#email').type('mike.smith@gmail.com')
        cy.get('#pass').type('12345678')
        cy.get('#send2').click()
        cy.get('.current').click()
        cy.get(':nth-child(4) > .col2-set > .col-1 > .box > .box-title > a')
        cy.get('#street_1').type('5th avenue,California')
        cy.get('#city').type('California')
        cy.get('#region').type('California')
        cy.get('#zip').type('90012')
        cy.get('#country').select('United States')
        cy.get('.buttons-set > .button').click()
    })
    it('Check the Add new address functionality', () => {
        cy.get('.skip-account').click()
        cy.get('#header-account > .links > ul > .last > a').click()
        cy.get('#email').type('mike.smith@gmail.com')
        cy.get('#pass').type('12345678')
        cy.get('#send2').should('be.visible')
        cy.get('#send2').click()
        cy.get('.block-content > ul > :nth-child(3) > a').should('be.visible')
        cy.get('.block-content > ul > :nth-child(3) > a').click()
        cy.get('.page-title > .button').should('be.visible')
        cy.get('.page-title > .button').click()
        cy.get('#telephone').type('0987654321')
        cy.get('#street_1').type('6th Avenue')
        cy.get('#city').type('California')
        cy.get('#region_id').select('California')
        cy.get('#zip').type('90013')
        cy.get('#country').type('United States')
        cy.get('.buttons-set > .button').should('be.visible')
        cy.get('.buttons-set > .button').click()
        cy.get('body > div > div > div.main-container.col2-left-layout > div > div.col-main > div > ul > li > ul > li > span').should('have.text','The address has been saved.')
        
      
    })
    it.only('Check the Wishlist functionality', () => {
        cy.get('.skip-account').click()
        cy.get('#header-account > .links > ul > :nth-child(2) > a').click()
        cy.get('#email').type('mike.smith@gmail.com')
        cy.get('#pass').type('12345678')
        cy.get('#send2').should('be.visible')
        cy.get('#send2').click()
        cy.get('.nav-1 > .level0').should('be.visible')
        cy.get('.nav-1 > .level0').click()
        cy.get(':nth-child(2) > .product-info > .actions > .add-to-links > :nth-child(1) > .link-wishlist').click()
        cy.get('.nav-2 > .level0').should('be.visible')
        cy.get('.nav-2 > .level0').click()
        cy.get(':nth-child(1) > .product-info > .actions > .add-to-links > :nth-child(1) > .link-wishlist').click()
        cy.get('.header-minicart > .skip-link').should('be.visible')
        cy.get('.header-minicart > .skip-link').click()
        cy.get('.skip-account').should('be.visible')
        cy.get('.skip-account').click()
        cy.get('#header-account > .links > ul > :nth-child(2) > a').should('be.visible')
        cy.get('#header-account > .links > ul > :nth-child(2) > a').click()
        cy.get('#item_51756 > .wishlist-cell5 > .btn-remove').should('be.visible')
        cy.get('#item_51756 > .wishlist-cell5 > .btn-remove').click()
    })
    

})    


